all: build test
GO_OUT := .


DB_DRIVER := mysql
DB_DSN  := 
MIGRATION_DIR := ./backend/migrations

all: build

build:
	go build -o bin/$(APP_NAME) ./cmd

dev:
	@echo "Starting development server..."
	cd backend && go run ./cmd/server

test:
	go test ./...

clean:
	rm -rf bin

migration-create:
	@if [ -z "$(name)" ]; then \
		echo "Usage: make migration-create name=create_users_table"; \
		exit 1; \
	fi
	goose -dir $(MIGRATION_DIR) create $(name) sql

migration-up:
	goose -dir $(MIGRATION_DIR) $(DB_DRIVER) "$(DB_DSN)" up

migration-down:
	goose -dir $(MIGRATION_DIR) $(DB_DRIVER) "$(DB_DSN)" down

migration-status:
	goose -dir $(MIGRATION_DIR) $(DB_DRIVER) "$(DB_DSN)" status

seed:
	@echo "Running database seeder..."
	cd backend && go run ./cmd/seed

gen-doc:
	@echo "Generating swagger docs..."
	cd backend && swag init -g ./cmd/server/main.go -o ../docs

# Help
run-dev:
	@make gen-doc
	@make dev

# ===============================
# DECLARE PHONY
# ===============================
.PHONY: all build run test clean \
        migration-create migration-up migration-down migration-status seed gen-doc run-with-docs
