all: build test
PROTO_DIR := proto
PROTO_SRC := $(wildcard $(PROTO_DIR)/*.proto)
GO_OUT := .

POSTGRES_URI := 


//make migration-create name=create_users_table
migration-create:
	goose -dir ./backend/migrations create $(name) sql

migration-up:
	goose -dir ./backend/migrations postgres $(POSTGRES_URI) up

migration-down:
	goose -dir ./backend/migrations postgres $(POSTGRES_URI) down


.PHONY: all build run test clean watch docker-run docker-down itest
